# Generated by Django 3.1.6 on 2023-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCar', '0002_auto_20230811_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='photo',
            field=models.ImageField(upload_to='src/cars/'),
        ),
    ]
