# Generated by Django 3.1.6 on 2023-08-11 10:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCar', '0003_auto_20230811_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, max_length=255, unique=True),
        ),
    ]
