# Generated by Django 3.1.6 on 2023-08-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCar', '0007_auto_20230811_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
